# Generated by Django 2.2.2 on 2019-07-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.TextField()),
                ('client_city', models.TextField(blank=True, null=True)),
                ('client_state', models.TextField(blank=True, null=True)),
                ('client_since', models.DateField()),
                ('phone_number', models.TextField()),
            ],
        ),
    ]
