# Generated by Django 2.2.2 on 2019-07-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='sectors.Sector'),
        ),
    ]
