# Generated by Django 2.2.2 on 2019-07-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='Shows',
        ),
    ]
