# Generated by Django 2.2.2 on 2019-07-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20190704_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='client_name',
        ),
        migrations.AddField(
            model_name='show',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
