# Generated by Django 2.2.2 on 2019-07-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
